version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "StrongPwd123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./englishlearning.sql:/englishlearning.sql

  englishlearning:
    image: englishlearning
    build:
      context: .
      dockerfile: EnglishLearning/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=EnglishLearningDB;User Id=sa;Password=StrongPwd123!;TrustServerCertificate=True
    ports:
      - "5000:5000"
      - "5001:5001"
volumes:
  sqlserverdata: